// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: history.sql

package store

import (
	"context"
)

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO history (method, url, status, duration_ms, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertHistoryParams struct {
	Method     string `json:"method"`
	Url        string `json:"url"`
	Status     int64  `json:"status"`
	DurationMs int64  `json:"durationMs"`
	CreatedAt  int64  `json:"createdAt"`
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertHistory,
		arg.Method,
		arg.Url,
		arg.Status,
		arg.DurationMs,
		arg.CreatedAt,
	)
	return err
}

const listHistory = `-- name: ListHistory :many
SELECT id, method, url, status, duration_ms, created_at
FROM history
ORDER BY created_at DESC, id DESC
LIMIT ?
`

func (q *Queries) ListHistory(ctx context.Context, limit int64) ([]History, error) {
	rows, err := q.db.QueryContext(ctx, listHistory, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []History
	for rows.Next() {
		var i History
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.Url,
			&i.Status,
			&i.DurationMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
