// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

type History struct {
	ID         int64  `json:"id"`
	Method     string `json:"method"`
	Url        string `json:"url"`
	Status     int64  `json:"status"`
	DurationMs int64  `json:"durationMs"`
	CreatedAt  int64  `json:"createdAt"`
}
