// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_settings.sql

package store

import (
	"context"
)

const getFollowRedirects = `-- name: GetFollowRedirects :one
SELECT follow_redirects FROM request_settings WHERE request_id = ?
`

func (q *Queries) GetFollowRedirects(ctx context.Context, requestID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFollowRedirects, requestID)
	var follow_redirects int64
	err := row.Scan(&follow_redirects)
	return follow_redirects, err
}

const putFollowRedirects = `-- name: PutFollowRedirects :exec
INSERT INTO request_settings (request_id, follow_redirects) VALUES (?, ?)
ON CONFLICT (request_id) DO UPDATE SET follow_redirects = excluded.follow_redirects
`

type PutFollowRedirectsParams struct {
	RequestID       string `json:"requestId"`
	FollowRedirects int64  `json:"followRedirects"`
}

func (q *Queries) PutFollowRedirects(ctx context.Context, arg PutFollowRedirectsParams) error {
	_, err := q.db.ExecContext(ctx, putFollowRedirects, arg.RequestID, arg.FollowRedirects)
	return err
}
