// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: request_settings.sql

package store

import (
	"context"
)

const deleteFollowRedirects = `-- name: DeleteFollowRedirects :exec
DELETE FROM request_settings WHERE request_id = ?
`

func (q *Queries) DeleteFollowRedirects(ctx context.Context, requestID string) error {
	_, err := q.db.ExecContext(ctx, deleteFollowRedirects, requestID)
	return err
}

const listRequestSettings = `-- name: ListRequestSettings :many

SELECT request_id, follow_redirects FROM request_settings ORDER BY request_id
`

// The request_settings table held per-request follow-redirects overrides before
// the setting moved to the server. These queries only serve the one-time push of
// leftover rows to the server (then the table is dropped).
func (q *Queries) ListRequestSettings(ctx context.Context) ([]RequestSetting, error) {
	rows, err := q.db.QueryContext(ctx, listRequestSettings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RequestSetting
	for rows.Next() {
		var i RequestSetting
		if err := rows.Scan(&i.RequestID, &i.FollowRedirects); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putFollowRedirects = `-- name: PutFollowRedirects :exec
INSERT INTO request_settings (request_id, follow_redirects) VALUES (?, ?)
ON CONFLICT (request_id) DO UPDATE SET follow_redirects = excluded.follow_redirects
`

type PutFollowRedirectsParams struct {
	RequestID       string `json:"requestId"`
	FollowRedirects int64  `json:"followRedirects"`
}

func (q *Queries) PutFollowRedirects(ctx context.Context, arg PutFollowRedirectsParams) error {
	_, err := q.db.ExecContext(ctx, putFollowRedirects, arg.RequestID, arg.FollowRedirects)
	return err
}
