// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: secret_values.sql

package store

import (
	"context"
)

const deleteSecretValue = `-- name: DeleteSecretValue :exec
DELETE FROM secret_values WHERE environment_id = ? AND key = ?
`

type DeleteSecretValueParams struct {
	EnvironmentID string `json:"environmentId"`
	Key           string `json:"key"`
}

func (q *Queries) DeleteSecretValue(ctx context.Context, arg DeleteSecretValueParams) error {
	_, err := q.db.ExecContext(ctx, deleteSecretValue, arg.EnvironmentID, arg.Key)
	return err
}

const deleteSecretValuesForEnvironment = `-- name: DeleteSecretValuesForEnvironment :exec
DELETE FROM secret_values WHERE environment_id = ?
`

func (q *Queries) DeleteSecretValuesForEnvironment(ctx context.Context, environmentID string) error {
	_, err := q.db.ExecContext(ctx, deleteSecretValuesForEnvironment, environmentID)
	return err
}

const getSecretValue = `-- name: GetSecretValue :one
SELECT value FROM secret_values WHERE environment_id = ? AND key = ?
`

type GetSecretValueParams struct {
	EnvironmentID string `json:"environmentId"`
	Key           string `json:"key"`
}

func (q *Queries) GetSecretValue(ctx context.Context, arg GetSecretValueParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSecretValue, arg.EnvironmentID, arg.Key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listSecretValues = `-- name: ListSecretValues :many
SELECT key, value FROM secret_values WHERE environment_id = ? ORDER BY key
`

type ListSecretValuesRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) ListSecretValues(ctx context.Context, environmentID string) ([]ListSecretValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecretValues, environmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecretValuesRow
	for rows.Next() {
		var i ListSecretValuesRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putSecretValue = `-- name: PutSecretValue :exec
INSERT INTO secret_values (environment_id, key, value) VALUES (?, ?, ?)
ON CONFLICT (environment_id, key) DO UPDATE SET value = excluded.value
`

type PutSecretValueParams struct {
	EnvironmentID string `json:"environmentId"`
	Key           string `json:"key"`
	Value         string `json:"value"`
}

func (q *Queries) PutSecretValue(ctx context.Context, arg PutSecretValueParams) error {
	_, err := q.db.ExecContext(ctx, putSecretValue, arg.EnvironmentID, arg.Key, arg.Value)
	return err
}

const renameSecretKey = `-- name: RenameSecretKey :exec
UPDATE OR REPLACE secret_values SET key = ?1
WHERE environment_id = ?2 AND key = ?3
`

type RenameSecretKeyParams struct {
	NewKey        string `json:"newKey"`
	EnvironmentID string `json:"environmentId"`
	OldKey        string `json:"oldKey"`
}

// Moves a value to a new key; OR REPLACE drops a value already stored under it.
func (q *Queries) RenameSecretKey(ctx context.Context, arg RenameSecretKeyParams) error {
	_, err := q.db.ExecContext(ctx, renameSecretKey, arg.NewKey, arg.EnvironmentID, arg.OldKey)
	return err
}
