// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {session} from '../models';
import {api} from '../models';

export function AcceptInvitation(arg1:string):Promise<main.AcceptedInvitationResult>;

export function CancelRequest(arg1:string):Promise<void>;

export function ConfirmQuit():Promise<void>;

export function CreateEnvironment(arg1:string,arg2:string):Promise<main.EnvironmentResult>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<main.FolderResult>;

export function CreateInvitation(arg1:string,arg2:string):Promise<main.InvitationResult>;

export function CreateProject(arg1:string,arg2:string):Promise<main.ProjectResult>;

export function CreateRequest(arg1:string,arg2:string,arg3:string):Promise<main.RequestSummaryResult>;

export function CreateTeam(arg1:string):Promise<main.TeamRefResult>;

export function CreateVariable(arg1:string,arg2:string,arg3:string):Promise<main.VariableResult>;

export function DeleteEnvironment(arg1:string,arg2:string):Promise<main.EmptyResult>;

export function DeleteFolder(arg1:string):Promise<main.EmptyResult>;

export function DeleteProject(arg1:string):Promise<main.EmptyResult>;

export function DeleteRequest(arg1:string):Promise<main.EmptyResult>;

export function DeleteSecretValue(arg1:string,arg2:string):Promise<main.EmptyResult>;

export function DeleteTeam(arg1:string):Promise<main.EmptyResult>;

export function DeleteVariable(arg1:string):Promise<main.EmptyResult>;

export function DuplicateRequest(arg1:string):Promise<main.RequestSummaryResult>;

export function GetAuthState():Promise<session.AuthState>;

export function GetEnvContext(arg1:string):Promise<main.EnvContextResult>;

export function GetMemberAccess(arg1:string,arg2:string):Promise<main.MemberAccessViewResult>;

export function GetProject(arg1:string):Promise<main.ProjectResult>;

export function GetProjectAccess(arg1:string):Promise<main.ProjectAccessUserListResult>;

export function GetRequest(arg1:string):Promise<main.RequestResult>;

export function GetSecretValue(arg1:string,arg2:string):Promise<string>;

export function GetSecretValues(arg1:string):Promise<Record<string, string>>;

export function GetSettings():Promise<main.Settings>;

export function GetTabs(arg1:string):Promise<main.Tabs>;

export function GetTeam(arg1:string):Promise<main.TeamResult>;

export function GetTheme():Promise<string>;

export function GetTreeState(arg1:string):Promise<Array<string>>;

export function GetUIPrefs():Promise<main.UIPrefs>;

export function ListFolders(arg1:string):Promise<main.FolderListResult>;

export function ListMyInvitations():Promise<main.MyInvitationListResult>;

export function ListProjects(arg1:string):Promise<main.ProjectListResult>;

export function ListRequests(arg1:string):Promise<main.RequestListResult>;

export function ListTeamInvitations(arg1:string):Promise<main.TeamInvitationListResult>;

export function ListTeams():Promise<main.TeamListResult>;

export function ListVariables(arg1:string):Promise<main.VariableViewListResult>;

export function LoadWorkspace():Promise<main.WorkspaceResult>;

export function Login(arg1:string,arg2:string):Promise<session.Result>;

export function Logout():Promise<session.AuthState>;

export function MoveEnvironment(arg1:string,arg2:string,arg3:number):Promise<main.EmptyResult>;

export function MoveFolder(arg1:string,arg2:string):Promise<main.FolderResult>;

export function MoveProject(arg1:string,arg2:string,arg3:number):Promise<main.EmptyResult>;

export function MoveRequest(arg1:string,arg2:string):Promise<main.RequestSummaryResult>;

export function MoveVariable(arg1:string,arg2:string,arg3:number):Promise<main.EmptyResult>;

export function PlaceNode(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>):Promise<main.EmptyResult>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<session.Result>;

export function RejectInvitation(arg1:string):Promise<main.EmptyResult>;

export function RemoveMember(arg1:string,arg2:string):Promise<main.EmptyResult>;

export function RenameEnvironment(arg1:string,arg2:string):Promise<main.EnvironmentResult>;

export function RenameFolder(arg1:string,arg2:string):Promise<main.FolderResult>;

export function ReorderFolders(arg1:string,arg2:string,arg3:Array<string>):Promise<main.EmptyResult>;

export function ReorderProjects(arg1:string,arg2:Array<string>):Promise<main.EmptyResult>;

export function ReorderRequests(arg1:string,arg2:string,arg3:Array<string>):Promise<main.EmptyResult>;

export function RevokeInvitation(arg1:string):Promise<main.EmptyResult>;

export function SaveRequest(arg1:string,arg2:api.RequestDraft,arg3:api.RequestDraft):Promise<main.RequestResult>;

export function SelectProject(arg1:string):Promise<main.WorkspaceResult>;

export function SelectTeam(arg1:string):Promise<main.WorkspaceResult>;

export function SendRequest(arg1:string,arg2:string,arg3:api.RequestDraft):Promise<main.SendResult>;

export function SetActiveEnvironment(arg1:string,arg2:string):Promise<main.EnvContextResult>;

export function SetMemberAccess(arg1:string,arg2:string,arg3:boolean,arg4:Array<string>):Promise<main.MemberAccessResult>;

export function SetProjectAccess(arg1:string,arg2:Array<string>):Promise<main.ProjectAccessResult>;

export function SetResponseWrap(arg1:boolean):Promise<main.EmptyResult>;

export function SetSecretValue(arg1:string,arg2:string,arg3:string):Promise<main.EmptyResult>;

export function SetServerURL(arg1:string):Promise<session.Result>;

export function SetSidebarWidth(arg1:number):Promise<main.EmptyResult>;

export function SetTabs(arg1:string,arg2:main.Tabs):Promise<main.EmptyResult>;

export function SetTheme(arg1:string):Promise<main.EmptyResult>;

export function SetTreeState(arg1:string,arg2:Array<string>):Promise<main.EmptyResult>;

export function SetVariableKey(arg1:string,arg2:string,arg3:string):Promise<main.EmptyResult>;

export function SetVariableType(arg1:string,arg2:string,arg3:string):Promise<main.EmptyResult>;

export function SetVariableValue(arg1:string,arg2:string,arg3:string):Promise<main.EmptyResult>;

export function UpdateProjectName(arg1:string,arg2:string):Promise<main.ProjectResult>;

export function UpdateRequest(arg1:string,arg2:api.RequestPatch):Promise<main.RequestResult>;

export function UpdateTeamName(arg1:string,arg2:string):Promise<main.TeamResult>;
