// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {session} from '../models';
import {main} from '../models';
import {store} from '../models';
import {engine} from '../models';

export function GetAuthState():Promise<session.AuthState>;

export function GetSettings():Promise<main.Settings>;

export function History():Promise<Array<store.History>>;

export function Login(arg1:string,arg2:string):Promise<session.Result>;

export function Logout():Promise<session.AuthState>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<session.Result>;

export function Send(arg1:engine.RequestSpec):Promise<engine.Response>;

export function SetServerURL(arg1:string):Promise<session.Result>;
