// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function History() {
  return window['go']['main']['App']['History']();
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
