// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptInvitation(arg1) {
  return window['go']['main']['App']['AcceptInvitation'](arg1);
}

export function CreateInvitation(arg1, arg2) {
  return window['go']['main']['App']['CreateInvitation'](arg1, arg2);
}

export function CreateTeam(arg1) {
  return window['go']['main']['App']['CreateTeam'](arg1);
}

export function DeleteTeam(arg1) {
  return window['go']['main']['App']['DeleteTeam'](arg1);
}

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTeam(arg1) {
  return window['go']['main']['App']['GetTeam'](arg1);
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function ListMyInvitations() {
  return window['go']['main']['App']['ListMyInvitations']();
}

export function ListTeamInvitations(arg1) {
  return window['go']['main']['App']['ListTeamInvitations'](arg1);
}

export function ListTeams() {
  return window['go']['main']['App']['ListTeams']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RejectInvitation(arg1) {
  return window['go']['main']['App']['RejectInvitation'](arg1);
}

export function RemoveMember(arg1, arg2) {
  return window['go']['main']['App']['RemoveMember'](arg1, arg2);
}

export function RevokeInvitation(arg1) {
  return window['go']['main']['App']['RevokeInvitation'](arg1);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function UpdateTeamName(arg1, arg2) {
  return window['go']['main']['App']['UpdateTeamName'](arg1, arg2);
}
