// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {session} from '../models';
import {store} from '../models';
import {engine} from '../models';

export function AcceptInvitation(arg1:string):Promise<main.AcceptedInvitationResult>;

export function CreateInvitation(arg1:string,arg2:string):Promise<main.InvitationResult>;

export function CreateTeam(arg1:string):Promise<main.TeamRefResult>;

export function DeleteTeam(arg1:string):Promise<main.EmptyResult>;

export function GetAuthState():Promise<session.AuthState>;

export function GetSettings():Promise<main.Settings>;

export function GetTeam(arg1:string):Promise<main.TeamResult>;

export function History():Promise<Array<store.History>>;

export function ListMyInvitations():Promise<main.MyInvitationListResult>;

export function ListTeamInvitations(arg1:string):Promise<main.TeamInvitationListResult>;

export function ListTeams():Promise<main.TeamListResult>;

export function Login(arg1:string,arg2:string):Promise<session.Result>;

export function Logout():Promise<session.AuthState>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<session.Result>;

export function RejectInvitation(arg1:string):Promise<main.EmptyResult>;

export function RemoveMember(arg1:string,arg2:string):Promise<main.EmptyResult>;

export function RevokeInvitation(arg1:string):Promise<main.EmptyResult>;

export function Send(arg1:engine.RequestSpec):Promise<engine.Response>;

export function SetServerURL(arg1:string):Promise<session.Result>;

export function UpdateTeamName(arg1:string,arg2:string):Promise<main.TeamResult>;
