// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptInvitation(arg1) {
  return window['go']['main']['App']['AcceptInvitation'](arg1);
}

export function CancelRequest(arg1) {
  return window['go']['main']['App']['CancelRequest'](arg1);
}

export function ConfirmQuit() {
  return window['go']['main']['App']['ConfirmQuit']();
}

export function CreateEnvironment(arg1, arg2) {
  return window['go']['main']['App']['CreateEnvironment'](arg1, arg2);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreateInvitation(arg1, arg2) {
  return window['go']['main']['App']['CreateInvitation'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function CreateRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateRequest'](arg1, arg2, arg3);
}

export function CreateTeam(arg1) {
  return window['go']['main']['App']['CreateTeam'](arg1);
}

export function CreateVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateVariable'](arg1, arg2, arg3);
}

export function DeleteEnvironment(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1, arg2);
}

export function DeleteFolder(arg1) {
  return window['go']['main']['App']['DeleteFolder'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteRequest(arg1) {
  return window['go']['main']['App']['DeleteRequest'](arg1);
}

export function DeleteSecretValue(arg1, arg2) {
  return window['go']['main']['App']['DeleteSecretValue'](arg1, arg2);
}

export function DeleteTeam(arg1) {
  return window['go']['main']['App']['DeleteTeam'](arg1);
}

export function DeleteVariable(arg1) {
  return window['go']['main']['App']['DeleteVariable'](arg1);
}

export function DuplicateRequest(arg1) {
  return window['go']['main']['App']['DuplicateRequest'](arg1);
}

export function GetAuthState() {
  return window['go']['main']['App']['GetAuthState']();
}

export function GetEnvContext(arg1) {
  return window['go']['main']['App']['GetEnvContext'](arg1);
}

export function GetFollowRedirectsDefault() {
  return window['go']['main']['App']['GetFollowRedirectsDefault']();
}

export function GetMemberAccess(arg1, arg2) {
  return window['go']['main']['App']['GetMemberAccess'](arg1, arg2);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectAccess(arg1) {
  return window['go']['main']['App']['GetProjectAccess'](arg1);
}

export function GetRequest(arg1) {
  return window['go']['main']['App']['GetRequest'](arg1);
}

export function GetRequestRedirects(arg1) {
  return window['go']['main']['App']['GetRequestRedirects'](arg1);
}

export function GetSecretValue(arg1, arg2) {
  return window['go']['main']['App']['GetSecretValue'](arg1, arg2);
}

export function GetSecretValues(arg1) {
  return window['go']['main']['App']['GetSecretValues'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetTabs(arg1) {
  return window['go']['main']['App']['GetTabs'](arg1);
}

export function GetTeam(arg1) {
  return window['go']['main']['App']['GetTeam'](arg1);
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function GetTreeState(arg1) {
  return window['go']['main']['App']['GetTreeState'](arg1);
}

export function GetUIPrefs() {
  return window['go']['main']['App']['GetUIPrefs']();
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListMyInvitations() {
  return window['go']['main']['App']['ListMyInvitations']();
}

export function ListProjects(arg1) {
  return window['go']['main']['App']['ListProjects'](arg1);
}

export function ListRequests(arg1) {
  return window['go']['main']['App']['ListRequests'](arg1);
}

export function ListTeamInvitations(arg1) {
  return window['go']['main']['App']['ListTeamInvitations'](arg1);
}

export function ListTeams() {
  return window['go']['main']['App']['ListTeams']();
}

export function ListVariables(arg1) {
  return window['go']['main']['App']['ListVariables'](arg1);
}

export function LoadWorkspace() {
  return window['go']['main']['App']['LoadWorkspace']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MoveEnvironment(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveEnvironment'](arg1, arg2, arg3);
}

export function MoveFolder(arg1, arg2) {
  return window['go']['main']['App']['MoveFolder'](arg1, arg2);
}

export function MoveProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveProject'](arg1, arg2, arg3);
}

export function MoveRequest(arg1, arg2) {
  return window['go']['main']['App']['MoveRequest'](arg1, arg2);
}

export function MoveVariable(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveVariable'](arg1, arg2, arg3);
}

export function PlaceNode(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['PlaceNode'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function RejectInvitation(arg1) {
  return window['go']['main']['App']['RejectInvitation'](arg1);
}

export function ReleaseResponse(arg1) {
  return window['go']['main']['App']['ReleaseResponse'](arg1);
}

export function RemoveMember(arg1, arg2) {
  return window['go']['main']['App']['RemoveMember'](arg1, arg2);
}

export function RenameEnvironment(arg1, arg2) {
  return window['go']['main']['App']['RenameEnvironment'](arg1, arg2);
}

export function RenameFolder(arg1, arg2) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2);
}

export function ReorderFolders(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderFolders'](arg1, arg2, arg3);
}

export function ReorderProjects(arg1, arg2) {
  return window['go']['main']['App']['ReorderProjects'](arg1, arg2);
}

export function ReorderRequests(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderRequests'](arg1, arg2, arg3);
}

export function RevokeInvitation(arg1) {
  return window['go']['main']['App']['RevokeInvitation'](arg1);
}

export function SaveRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveRequest'](arg1, arg2, arg3);
}

export function SaveResponseToFile(arg1) {
  return window['go']['main']['App']['SaveResponseToFile'](arg1);
}

export function SelectProject(arg1) {
  return window['go']['main']['App']['SelectProject'](arg1);
}

export function SelectTeam(arg1) {
  return window['go']['main']['App']['SelectTeam'](arg1);
}

export function SendRequest(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2, arg3);
}

export function SetActiveEnvironment(arg1, arg2) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1, arg2);
}

export function SetFollowRedirectsDefault(arg1) {
  return window['go']['main']['App']['SetFollowRedirectsDefault'](arg1);
}

export function SetMemberAccess(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetMemberAccess'](arg1, arg2, arg3, arg4);
}

export function SetProjectAccess(arg1, arg2) {
  return window['go']['main']['App']['SetProjectAccess'](arg1, arg2);
}

export function SetRequestRedirects(arg1, arg2) {
  return window['go']['main']['App']['SetRequestRedirects'](arg1, arg2);
}

export function SetResponseWrap(arg1) {
  return window['go']['main']['App']['SetResponseWrap'](arg1);
}

export function SetSecretValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSecretValue'](arg1, arg2, arg3);
}

export function SetServerURL(arg1) {
  return window['go']['main']['App']['SetServerURL'](arg1);
}

export function SetSidebarWidth(arg1) {
  return window['go']['main']['App']['SetSidebarWidth'](arg1);
}

export function SetTabs(arg1, arg2) {
  return window['go']['main']['App']['SetTabs'](arg1, arg2);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetTreeState(arg1, arg2) {
  return window['go']['main']['App']['SetTreeState'](arg1, arg2);
}

export function SetVariableKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetVariableKey'](arg1, arg2, arg3);
}

export function SetVariableType(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetVariableType'](arg1, arg2, arg3);
}

export function SetVariableValue(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetVariableValue'](arg1, arg2, arg3);
}

export function UpdateProjectName(arg1, arg2) {
  return window['go']['main']['App']['UpdateProjectName'](arg1, arg2);
}

export function UpdateRequest(arg1, arg2) {
  return window['go']['main']['App']['UpdateRequest'](arg1, arg2);
}

export function UpdateTeamName(arg1, arg2) {
  return window['go']['main']['App']['UpdateTeamName'](arg1, arg2);
}
